name: easyleases_tenant
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.8+8

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dotted_border: ^0.1.1
  http: ^0.12.0+2
  flutter_bloc: ^0.15.1
  equatable: ^0.2.6
  email_validator: ^1.0.0
  shared_preferences: ^0.5.3+1
  device_info: ^0.4.0+2
  image_picker: ^0.6.0+9
  connectivity: ^0.4.4
  flutter_downloader: ^1.1.7
  path_provider: ^1.1.0
  permission_handler: '^3.1.0'
  flutter_webview_plugin: ^0.3.8
  file_picker: ^1.3.7
  intl: ^0.15.8
  cached_network_image: ^1.1.1
  share: ^0.5.3
  date_format: ^1.0.6
  flutter_cupertino_date_picker: ^1.0.12
  firebase_messaging: ^5.1.8
  url_launcher: ^5.1.0
  overlay_support: ^1.0.2
  pdf_render: ^0.57.1
  webview_flutter: ^0.3.15+1
  otp_count_down: ^1.0.6





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon_copy.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/dashboard_white.png
    - assets/icon/dashboard_gray.png
    - assets/icon/profile_white.png
    - assets/icon/profile_gray.png
    - assets/icon/agreements_white.png
    - assets/icon/agreements_gray.png
    - assets/icon/payment_white.png
    - assets/icon/payment_gray.png
    - assets/icon/service_requests_white.png
    - assets/icon/service_requests_gray.png
    - assets/icon/pencil_edit_button.png
    - assets/icon/document_white.png
    - assets/icon/add.png
    - assets/icon/delete.png
    - assets/icon/attachment.png
    - assets/icon/login_logo.png
    - assets/icon/blue_rectangle.png
    - assets/icon/red_rectangle.png
    - assets/icon/green_rectangle.jpeg
    - assets/icon/orange_rectangle.png
    - assets/icon/background_image.png
    - assets/team.png
    - assets/mission.png
    - assets/vision.png
    - assets/green_icon.png
    - assets/icon/photo_camera.png
    - assets/icon/delete_icon.png
    - assets/icon/back_arrow.png
    - assets/icon/attachment_new.png
    - assets/icon/drop_down_arrow.png
    - assets/icon/orange_rectangle.png
    - assets/icon/documents.png
    - assets/icon/bank_details_.png
    - assets/icon/employement.png
    - assets/icon/emergency.png
    - assets/sample.pdf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
